# Generated by Django 3.2.8 on 2021-10-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_add_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='edit_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='edit_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
